# Generated by Django 4.0.4 on 2022-05-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(choices=[('account', '계정'), ('general', '일반'), ('other', '기타')], default='general', max_length=8, verbose_name='문의분류')),
                ('title', models.TextField(blank=True, max_length=30, verbose_name='제목')),
                ('email', models.EmailField(default='honggildong@example.com', max_length=254, verbose_name='이메일')),
                ('email_btn', models.BooleanField(default=False, verbose_name='이메일로답변수신')),
                ('message', models.CharField(default='-없이 입력해 주세요', max_length=11, verbose_name='전화번호')),
                ('message_btn', models.BooleanField(default=False, verbose_name='문자메세지수신')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 일자')),
                ('finish', models.BooleanField(default=False, verbose_name='답변완료여부')),
                ('last_updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_updater_name', to=settings.AUTH_USER_MODEL, verbose_name='최종수정자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_writer_name', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='질문')),
                ('cartegori', models.CharField(choices=[('account', '계정'), ('general', '일반'), ('other', '기타')], default='general', max_length=8, verbose_name='카테고리')),
                ('answer', models.TextField(blank=True, verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='최종수정일')),
                ('last_updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fap_updater_name', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fap_writer_name', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='답변내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='최종수정일시')),
                ('Inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry', verbose_name='참조 문의글')),
                ('last_updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_updater_name', to=settings.AUTH_USER_MODEL, verbose_name='최종수정자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_writer_name', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
