# Generated by Django 4.0.4 on 2022-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='condition_category',
            field=models.CharField(choices=[('register', '문의 등록'), ('Received', '접수 완료'), ('finish', '답변 완료')], default='register', max_length=8, verbose_name='상태'),
        ),
    ]
